---
version: 2
registries:
  github-niq:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_ORG_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - actions
      - dependencies
    open-pull-requests-limit: 10
    registries:
      - github-niq
  - package-ecosystem: gomod
    directories:
      - /
    schedule:
      interval: daily
    labels:
      - dependencies
      - go
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directories:
      - /
    schedule:
      interval: daily
    labels:
      - dependencies
      - docker
    open-pull-requests-limit: 10
