apiVersion: v1
kind: Secret
metadata:
  name: github-stats-secrets
type: Opaque
stringData:
  org-a.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    REPLACE_WITH_ORG_A_KEY
    -----END RSA PRIVATE KEY-----
