---
apiVersion: v1
kind: Service
metadata:
  name: github-stats-exporter-metrics
  labels:
    app: github-stats-exporter
    app.kubernetes.io/component: exporter
spec:
  selector:
    app: github-stats-exporter
  ports:
    - name: http
      port: 8080
      targetPort: http
