---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: github-stats
  labels:
    app.kubernetes.io/component: exporter
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: github-stats
