---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-stats-exporter
labels:
  - pairs:
      app.kubernetes.io/name: github-stats-exporter
      app.kubernetes.io/instance: github-stats-exporter
      app.kubernetes.io/version: "0.0.0"
      app.kubernetes.io/part-of: github-stats-exporter
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
    includeTemplates: true
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service-http.yaml
  - app-service-metrics.yaml
  - app-pdb.yaml
  - dependencies-networkpolicy.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - redis-pdb.yaml
  - rabbitmq-service.yaml
  - rabbitmq-statefulset.yaml
  - rabbitmq-pdb.yaml
