---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-stats
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service-http.yaml
  - app-service-metrics.yaml
  - app-pdb.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - redis-pdb.yaml
  - rabbitmq-service.yaml
  - rabbitmq-statefulset.yaml
  - rabbitmq-pdb.yaml
