apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-stats-leader-election
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-stats-leader-election
subjects:
  - kind: ServiceAccount
    name: github-stats
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: github-stats-leader-election
