---
scrape_configs:
  - job_name: github-stats-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - github-stats-exporter-metrics.github-stats-exporter.svc.cluster.local:8080
